# Generated by Django 2.0 on 2018-01-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_auto_20180125_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cart',
            name='taxs',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=4),
        ),
    ]
