# Generated by Django 2.0 on 2018-01-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
