# Generated by Django 2.0 on 2018-01-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0003_auto_20180126_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Cart.Cart'),
        ),
    ]
