# Generated by Django 2.0 on 2018-01-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0006_auto_20180127_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cart.Cart'),
        ),
    ]
