# Generated by Django 2.0 on 2018-01-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0007_auto_20180127_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
