# Generated by Django 2.0 on 2018-01-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0008_invoice_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
